
FROM postgres:latest


ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=${POSTGRES_DB}


COPY database.py /docker-entrypoint-initdb.d/
COPY values.py /docker-entrypoint-initdb.d/


EXPOSE 5432
