version: '3'
services:
  database:
    build:
      context: . 
      dockerfile: Dockerfile.database
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB} 

  tg_bot:
    build:
      context: .
      dockerfile: Dockerfile.tg_bot
    depends_on:
      - database 
